name: Azure Web APp deployment
on:
  workflow_call:
    inputs:
      config_file:
        required: true
        type: string
        description: Config file path
      environment:
        required: true
        type: string
        description: Environment to deploy to
  workflow_dispatch:
    inputs:
      config_file:
        required: true
        type: string
        description: Config file path
      environment:
        required: true
        type: string
        description: Environment to deploy to

jobs:
  check-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Installs python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yq

      # Check kind
      - name: Check kind
        id: check-kind
        run: |
          echo "::set-output name=kind::$(yq -c -r '.kind' ${{ inputs.config_file }})"
    outputs:
      kind: ${{ steps.check-kind.outputs.kind }}
  deployment:
    needs: check-kind
    if: contains('web_app', needs.check-kind.outputs.kind)
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Installs python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yq

      - name: Gather parameters
        id: parameters
        run: | 
          echo "Gathering parameters"
          echo "::set-output name=artifact_location::$(yq -c -r '.artifact_location' ${{ inputs.config_file }})"
          echo "::set-output name=artifact_name::$(yq -c -r '.artifact_name' ${{ inputs.config_file }})"
          echo "::set-output name=artifact_version::$(yq -c -r '.artifact_version' ${{ inputs.config_file }})"

      - name: Downloading artifacts
        run: |
          mkdir -p target
          wget ${{ steps.parameters.outputs.artifact_location }}/v${{ steps.parameters.outputs.artifact_version }}/${{ steps.parameters.outputs.artifact_name }}-${{ steps.parameters.outputs.artifact_version }}.jar -O artifact.jar # change extension
# unzip artifact.zip -d target

      - name: Deploying web app
        run: |
          ls -l ./
          echo "Deploying web_app"
          echo "APP NAME: ${{ inputs.config_file }}"
          echo "ENVIRONMENT: ${{ inputs.environment }}"
