name: Create PR for changes in DEV

on:
  workflow_dispatch:
  push:
    paths:
      - dev/deployments.yaml
    branches:
      - auto-deployment-dev

jobs:
  create-pr:
    name: Create PR for DEV changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Creates pull request
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "[DEV] Versions update"
          pr_body: ":robot: **An automated PR** was created due to committed changes in `dev/deployments.yaml`."
