name: DEV env deployment

on:
  workflow_dispatch:
  push:
    paths:
      - dev/*.yml
    branches:
      - main

jobs:
  pre-deployment:
    name: Gathering changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Generates list of modified files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            dev/*.yml
      - id: set-matrix
        run: echo "::set-output name=matrix::[$(echo ${{ steps.changed-files.outputs.all_changed_files }} | sed 's/ /\",\"/g;s/^/\"/g;s/$/\"/g')]"
    outputs:
      deployments: ${{ steps.set-matrix.outputs.matrix }}

  dev-deployment:
    name: Deploying ${{ matrix.deployment }} to DEV environment
    needs: pre-deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment: ${{ fromJSON(needs.pre-deployment.outputs.deployments) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Running deployment
        run: echo "Deploying ${{ matrix.deployment }} to DEV"

  trigger-test-env:
    name: Propagate changes to Test env
    needs: dev-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Propagating changes to Test env
        run: cp -f dev/*.yml test/

      # Creates pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-deployment-test
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[TEST] Versions update"
          body: |
            :robot: **An automated PR** was created due to changes in **test/deployments.yml**.
            :information_source: By merging this PR, changes will be deployed to Test env!
          commit-message: "auto: propagating DEV changes to Test"
