name: DEV env deployment

on:
  workflow_dispatch:
  push:
    paths:
      - dev/*.yml
    branches:
      - main

env:
  environment: dev

jobs:
  pre-deployment:
    name: Gathering changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Generates list of modified files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            ${{ env.environment }}/*.yml
      # Exports list of changed files
      - id: set-matrix
        run: echo "::set-output name=matrix::[$(echo ${{ steps.changed-files.outputs.all_changed_files }} | sed 's/ /\",\"/g;s/^/\"/g;s/$/\"/g')]"
    outputs:
      changed_files_list: ${{ steps.set-matrix.outputs.matrix }}
      changed_files_str: ${{ steps.changed-files.outputs.all_changed_files }}


  # Deploy Azure function
  deployment-azure-function:
    needs: pre-deployment
    strategy:
      matrix:
        config: ${{ fromJSON(needs.pre-deployment.outputs.changed_files_list) }}
    uses: olehmart/test-deployments/.github/workflows/azure_function_deployment.yml@main
    with:
      config_file: ${{ matrix.config }}
      environment: development

  # Deploy Azure Web App
  deployment-azure-web-app:
    needs: pre-deployment
    strategy:
      matrix:
        config: ${{ fromJSON(needs.pre-deployment.outputs.changed_files_list) }}
    uses: olehmart/test-deployments/.github/workflows/azure_web_app_deployment.yml@main
    with:
      config_file: ${{ matrix.config }}
      environment: development

  trigger-test-env:
    name: Propagate changes to Test env
    needs: [pre-deployment, deployment-azure-function, deployment-azure-web-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Updating apps version
      - name: Propagating changes to Test env
        id: changes-propagate
        run: |
          /bin/bash .github/scripts/version_update.sh "${{ needs.pre-deployment.outputs.changed_files_str }}" test

      # Creates pull request
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v4
#        if: ${{ steps.changes-propagate.outputs.configs_updated }}
#        with:
#          branch: auto-deployment-test
#          base: "main"
#          token: ${{ secrets.GITHUB_TOKEN }}
#          title: "[AUTO][TEST] Versions update"
#          body: |
#            :robot: **An automated PR** was created due to changes in **test/*.yml**.
#            :information_source: By merging this PR, changes will be deployed to Test env!
#          commit-message: "auto: propagating DEV changes to Test"
#          labels: |
#            automated pr
      # Push changes
      - name: Push changes
        if: ${{ steps.changes-propagate.outputs.configs_updated }}
        run: |
          git config user.name GitHub BOT
          git config user.email noreply@github.com
          git add .
          git commit -m "auto: propagating DEV changes to Test"
          git push origin auto-deployment-test
      # Creates pull request
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        if: ${{ steps.changes-propagate.outputs.configs_updated }}
        with:
          source_branch: "auto-deployment-test"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "[AUTO][TEST] Versions update"
          pr_body: |
            :robot: **An automated PR** was created due to changes in **test/*.yml**.
            :information_source: By merging this PR, changes will be deployed to Test env!
          pr_label: "automated pr"
