name: DEV env deployment

on:
  workflow_dispatch:
  push:
    paths:
      - dev/*.yml
    branches:
      - main

env:
  environment: dev

jobs:
  pre-deployment:
    name: Gathering changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Generates list of modified files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            ${{ env.environment }}/*.yml
      # Exports list of changed files
      - id: set-matrix
        run: echo "::set-output name=matrix::[$(echo ${{ steps.changed-files.outputs.all_changed_files }} | sed 's/ /\",\"/g;s/^/\"/g;s/$/\"/g')]"
    outputs:
      changed_files_list: ${{ steps.set-matrix.outputs.matrix }}
      changed_files_str: ${{ steps.changed-files.outputs.all_changed_files }}


  # Deploy Azure function
  deployment-azure-function:
    needs: pre-deployment
    strategy:
      matrix:
        config: ${{ fromJSON(needs.pre-deployment.outputs.changed_files_list) }}
    uses: olehmart/test-deployments/.github/workflows/azure_function_deployment.yml@main
    with:
      config_file: ${{ matrix.config }}
      environment: development

  # Deploy Azure Web App
  deployment-azure-web-app:
    needs: pre-deployment
    strategy:
      matrix:
        config: ${{ fromJSON(needs.pre-deployment.outputs.changed_files_list) }}
    uses: olehmart/test-deployments/.github/workflows/azure_web_app_deployment.yml@main
    with:
      config_file: ${{ matrix.config }}
      environment: development

  trigger-test-env:
    name: Propagate changes to Test env
    needs: [pre-deployment, deployment-azure-function, deployment-azure-web-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Updating app version
      - name: Propagating changes to Test env
        run: |
          for config in ${{ needs.pre-deployment.outputs.changed_files_str }}
          do
            export new_version=$(cat ${config} | grep artifact_version | awk '{print $2}')
            export config_file_name=$(echo ${config} | awk -F/ '{print $(NF)}')
            sed -i "s/artifact_version: .*/artifact_version: ${new_version}/g" ${config_file_name}
          done

      # Creates pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-deployment-test
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[AUTO][TEST] Versions update"
          body: |
            :robot: **An automated PR** was created due to changes in **test/*.yml**.
            :information_source: By merging this PR, changes will be deployed to Test env!
          commit-message: "auto: propagating DEV changes to Test"
          labels: |
            automated pr
