name: DEV env deployment

on:
  workflow_dispatch:
  push:
    paths:
      - dev/*.yml
    branches:
      - main

env:
  environment: dev

jobs:
  pre-deployment:
    name: Gathering changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Generates list of modified files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            ${{ env.environment }}/*.yml
      # Exports list of changed files
      - id: set-matrix
        run: echo "::set-output name=matrix::[$(echo ${{ steps.changed-files.outputs.all_changed_files }} | sed 's/ /\",\"/g;s/^/\"/g;s/$/\"/g')]"
    outputs:
      deployments: ${{ steps.set-matrix.outputs.matrix }}

  kind-check:
    name: Checking kind of App
    environment: development
    needs: pre-deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment: ${{ fromJSON(needs.pre-deployment.outputs.deployments) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Installs python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yq

      # Export parameters
      - name: Export parameters
        id: parameters
        run: |
          echo "::set-output name=kind::$(yq -c -r '.kind' ${{ matrix.deployment }})"
    outputs:
      kind: ${{ steps.parameters.outputs.kind }}
  deployment-azure-function:
    needs: [kind-check, pre-deployment]
    strategy:
      matrix:
        deployment: ${{ fromJSON(needs.pre-deployment.outputs.deployments) }}
    # Calls actual deployment
    uses: olehmart/test-deployments/.github/workflows/azure_function_deployment.yml@main
    if: contains('azure_function', needs.kind-check.outputs.kind)
    with:
      app-name: ${{ matrix.deployment }}
      environment: development
  deployment-azure-web-app:
    needs: [ kind-check, pre-deployment ]
    strategy:
      matrix:
        deployment: ${{ fromJSON(needs.pre-deployment.outputs.deployments) }}
    # Calls actual deployment
    uses: olehmart/test-deployments/.github/workflows/azure_web_app_deployment.yml@main
    if: contains('web_app', needs.kind-check.outputs.kind)
    with:
      app-name: ${{ matrix.deployment }}
      environment: development

  trigger-test-env:
    name: Propagate changes to Test env
    needs: [deployment-azure-function, deployment-azure-web-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Copies all files from previous environment to the next one
      - name: Propagating changes to Test env
        run: cp -f ${{ env.environment }}/*.yml test/

      # Creates pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-deployment-test
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[AUTO][TEST] Versions update"
          body: |
            :robot: **An automated PR** was created due to changes in **test/deployments.yml**.
            :information_source: By merging this PR, changes will be deployed to Test env!
          commit-message: "auto: propagating DEV changes to Test"
          labels: |
            automated pr
