name: Stage env deployment

on:
  workflow_dispatch:
  push:
    paths:
      - stage/*.yml
    branches:
      - main

jobs:
  pre-deployment:
    name: Gathering changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Generates list of modified files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            stage/*.yml
      # Exports list of changed files
      - id: set-matrix
        run: echo "::set-output name=matrix::[$(echo ${{ steps.changed-files.outputs.all_changed_files }} | sed 's/ /\",\"/g;s/^/\"/g;s/$/\"/g')]"
    outputs:
      deployments: ${{ steps.set-matrix.outputs.matrix }}

  stage-deployment:
    name: Deploying ${{ matrix.deployment }} to Stage environment
    environment: stage
    needs: pre-deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment: ${{ fromJSON(needs.pre-deployment.outputs.deployments) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Installs python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yq

      # Export parameters
      - name: Export parameters
        id: parameters
        run: |
          echo "::set-output name=artifact_name::$(yq -c -r '.artifact_name' ${{ matrix.deployment }})"
          echo "::set-output name=artifact_location::$(yq -c -r '.artifact_location' ${{ matrix.deployment }})"
          echo "::set-output name=artifact_version::$(yq -c -r '.artifact_version' ${{ matrix.deployment }})"
          echo "::set-output name=deployment_script::$(yq -c -r '.deployment_script' ${{ matrix.deployment }})"
          echo "::set-output name=env_vars::$(yq -c -r '.env_vars' ${{ matrix.deployment }})"
          echo "::set-output name=kind::$(yq -c -r '.kind' ${{ matrix.deployment }})"

      # Deployment steps
      - name: Running deployment
        run: |
          echo "Deploying ${{ matrix.deployment }} to ${{ env.environment }} environment"
          echo "Artifact name: ${{ steps.parameters.outputs.artifact_name }}"
          echo "Artifact location: ${{ steps.parameters.outputs.artifact_location }}"
          echo "Artifact version: ${{ steps.parameters.outputs.artifact_version }}"
          echo "Env vars: ${{ steps.parameters.outputs.env_vars }}"
          echo "Kind: ${{ steps.parameters.outputs.kind }}"

  trigger-prod-env:
    name: Propagate changes to Prod env
    needs: stage-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Propagating changes to Prod env
        run: cp -f stage/*.yml prod/

      # Creates pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-deployment-prod
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[AUTO][PROD] Versions update"
          body: |
            :robot: **An automated PR** was created due to changes in **prod/*.yml**.
            :warning: :warning: :warning: By merging this PR, changes will be deployed to PROD env! :warning: :warning: :warning:
          commit-message: "auto: propagating Stage changes to Prod"
          labels: |
            automated pr
