name: Test env deployment

on:
  workflow_dispatch:
  push:
    paths:
      - test/deployments.yaml
    branches:
      - main

jobs:
  test-deployment:
    name: Deployment to Test environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Running deployment
        run: echo "Deploying to Test"

  trigger-stage-env:
    name: Propagate changes to Stage env
    needs: test-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Propagating changes to Stage env
        run: cp -f test/deployments.yaml stage/deployments.yaml

      # Creates pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-deployment-stage
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[STAGE] Versions update"
          body: ":robot: **An automated PR** was created due to committed changes in **stage/deployments.yaml**."
          commit-message: "auto: propagating Test changes to Stage"
