name: Test env deployment

on:
  workflow_dispatch:
  push:
    paths:
      - test/*.yml
    branches:
      - main

jobs:
  pre-deployment:
    name: Gathering changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Generates list of modified files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            test/*.yml
      # Exports list of changed files
      - id: set-matrix
        run: echo "::set-output name=matrix::[$(echo ${{ steps.changed-files.outputs.all_changed_files }} | sed 's/ /\",\"/g;s/^/\"/g;s/$/\"/g')]"
    outputs:
      deployments: ${{ steps.set-matrix.outputs.matrix }}

  test-deployment:
    name: Deploying ${{ matrix.deployment }} to Test environment
    environment: test
    needs: pre-deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment: ${{ fromJSON(needs.pre-deployment.outputs.deployments) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Deployment steps
      - name: Running deployment
        run: echo "Deploying ${{ matrix.deployment }} to Test"

  trigger-stage-env:
    name: Propagate changes to Stage env
    needs: test-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Propagating changes to Stage env
        run: cp -f test/*.yml stage/

      # Creates pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-deployment-stage
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[AUTO][STAGE] Versions update"
          body: |
            :robot: **An automated PR** was created due to changes in **stage/*.yml**.
            :information_source: By merging this PR, changes will be deployed to Stage env!
          commit-message: "auto: propagating Test changes to Stage"
